# Generated by Django 4.1 on 2022-09-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_recipe_picture_recipe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(to='menu.category'),
        ),
    ]
