# Generated by Django 4.1.1 on 2022-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_recipe_options_remove_recipe_ingridients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='col6',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='col7',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridient6',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridient7',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='col1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='col2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='col3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='col4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='col5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
