# Generated by Django 4.1.1 on 2022-10-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_recipe_col6_remove_recipe_col7_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('messages', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Ingridient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
        ),
        migrations.AddField(
            model_name='messages',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.recipe'),
        ),
    ]
